name: sincro
description: "Um aplicativo de gerenciamento de gastos financeiros que simplifica o controle de despesas individuais e compartilhadas através de um sistema de grupos."

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1

  device_info_plus: ^11.5.0

  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.0

  dio: ^5.9.0

  flutter_dotenv: ^6.0.0

  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.0

  fpdart: ^1.1.1

  go_router: ^16.2.4

  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.7.1
  freezed: ^3.2.3

  custom_lint: ^0.8.0
  flutter_lints: ^5.0.0
  riverpod_lint: ^3.0.0

  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.0

  mockito: ^5.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
